name: nilm312
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - scipy
  - pip
  - pip:
    - pulp
    - torch
    - coincbc>=2.10
